"""init schema

Revision ID: 3a73ef90d4c7
Revises: 
Create Date: 2026-06-15 16:34:05.738822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a73ef90d4c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('os_type', sa.Enum('linux', 'windows', name='os_type'), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=False),
    sa.Column('connection_mode', sa.Enum('agentless', 'agent', name='connection_mode'), nullable=False),
    sa.Column('ssh_credentials_enc', sa.Text(), nullable=True),
    sa.Column('agent_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', name='system_status'), nullable=False),
    sa.Column('last_audit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'auditor', 'readonly', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'revoked', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='audit_status'), nullable=False),
    sa.Column('score_global', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'moderate', 'high', 'critical', name='risk_level'), nullable=True),
    sa.Column('cis_level', sa.Enum('L1', 'L2', name='cis_level'), nullable=False),
    sa.Column('scores_by_domain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.Enum('access', 'network', 'logging', 'crypto', 'updates', 'services', name='domain'), nullable=False),
    sa.Column('cis_level', sa.Enum('L1', 'L2', name='cis_level_result'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'fail', 'warn', 'na', name='result_status'), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.Enum('dryrun', 'apply', name='remediation_mode'), nullable=False),
    sa.Column('script_type', sa.Enum('bash', 'powershell', 'ansible', name='script_type'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', name='remediation_status'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('remediation_logs')
    op.drop_table('audit_results')
    op.drop_table('audits')
    op.drop_table('users')
    op.drop_table('systems')
    # ### end Alembic commands ###
