"""add use_sudo to systems

Revision ID: b1c2d3e4f5a6
Revises: dd67f61a44ef
Create Date: 2026-06-17 18:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'dd67f61a44ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'use_sudo',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_column('use_sudo')

    # ### end Alembic commands ###
