"""add error_message to audits

Revision ID: dd67f61a44ef
Revises: 3a73ef90d4c7
Create Date: 2026-06-16 16:08:55.642887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd67f61a44ef'
down_revision = '3a73ef90d4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
